version: 2.0.{build}
os: Visual Studio 2017
configuration: Release
platform: x86
clone_folder: C:\projects\dnp3
environment: {}
install:
- git describe --tags --exact-match & cmd /c exit 0
- git submodule update --init --recursive
build_script:
- cmd: MKDIR build
- cmd: CD build
- cmd: cmake .. -DCMAKE_BUILD_TYPE=Release -DDNP3_TEST=ON -DDNP3_TLS=ON -DDNP3_DOTNET=ON
- cmd: cmake --build . --config Release
after_build:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true"){
      nuget pack c:\projects\dnp3\build\Release\opendnp3.nuspec -Version "$env:APPVEYOR_REPO_TAG_NAME"
    }
test_script:
- cmd: c:\projects\dnp3\build\Release\testasiodnp3.exe
- cmd: c:\projects\dnp3\build\Release\testasiopal.exe
- cmd: c:\projects\dnp3\build\Release\testopendnp3.exe
- cmd: c:\projects\dnp3\build\Release\testopenpal.exe
artifacts:
- path: '**\*.nupkg'
  name: nuget
deploy:
  provider: NuGet
  api_key:
    secure: FAIGIy0LoapVE4qvzWK9CP/E1j4lx8sMIsoCsKyi7F81BFN4wOEyMwFaiBPjsI+j
  on:
    appveyor_repo_tag: true  
