version: 2.0.{build}
branches:
  only:
  - 2.0.x
os: Visual Studio 2013
configuration: Release
platform: x86
clone_folder: C:\projects\dnp3
environment:
  ASIO_HOME: C:\asio\asio-1.10.6\include
  OSSL_LIB32_DIR: C:\OpenSSL-Win32\lib\VC
  OPENDNP3_DIR: C:\projects\dnp3\build\lib
install:
- ps: >-
    if (-not (Test-Path C:\asio)){
      Start-FileDownload "https://github.com/chriskohlhoff/asio/archive/asio-1-10-6.zip" -FileName asio-1-10-6.zip
      7z x -y asio-1-10-6.zip
      New-Item C:\asio -ItemType Directory
      Move-Item .\asio-asio-1-10-6\asio C:\asio\asio-1.10.6
    }
- ps: >-
    if (-not (Test-Path C:\OpenSSL-Win32)){
      Start-FileDownload "https://slproweb.com/download/Win32OpenSSL-1_0_2e.exe" -FileName "Win32OpenSSL-1_0_2e.exe"
      Start-Process "Win32OpenSSL-1_0_2e.exe" -ArgumentList "/silent /verysilent /sp- /suppressmsgboxes" -Wait
    }
cache:
- C:\asio
- C:\OpenSSL-Win32
nuget:
  project_feed: true
build_script:
- cmd: MKDIR build
- cmd: CD build
- cmd: MKDIR lib
- cmd: cmake .. -DCMAKE_INSTALL_PREFIX=lib -DFULL=ON -DCMAKE_BUILD_TYPE=Release
- cmd: msbuild opendnp3.sln /p:Configuration=Release /p:Platform=Win32
- cmd: msbuild INSTALL.vcxproj /p:Configuration=Release /p:Platform=Win32
- cmd: cd ..
- cmd: msbuild dotnet\bindings.sln /p:Configuration=Release /p:Platform=Win32
after_build:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG){
      nuget pack dotnet\nuget\opendnp3.nuspec -Version $env:APPVEYOR_REPO_TAG_NAME
    }
test_script:
- cmd: c:\projects\dnp3\build\Release\testopendnp3.exe
- cmd: c:\projects\dnp3\build\Release\testopenpal.exe
# deploy:
#   provider: NuGet
#   api_key:
#     secure: encrypted key https://ci.appveyor.com/tools/encrypt
#   on:
#     appveyor_repo_tag: true